site_name: Physical Starlight and Atmosphere
site_dir: psa
theme:
  name: material
  features:
    - tabs
plugins:
  - search
site_url: https://www.physicaladdons.com/psa/
google_analytics: ['UA-86947939-2', 'auto']
markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.keys
  - attr_list
  - abbr
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
nav:
#  - Home: index.md
  - Getting Started:
    - Installation: getting-started.md
    - Customization: customization.md
    - Updating: updating.md
    - Frequently Asked Questions: faq.md
  - Documentation:
    - Overview: overview.md
    - Presets: presets.md
    - Sun: sun.md
    - Binary Sun: binary-sun.md
#    - Atmosphere: atmosphere.md
    - Ground: ground.md
#    - Stars: stars.md
#    - Artistic Values: artistic-values.md
  - Changelog:
    - Release Notes: release-notes.md
  - About:
    - Physical Starlight and Atmosphere: about.md
    - Contacts: contacts.md
extra_css:
  - stylesheets/extra.css
